name       : rocsolver
version    : 5.5.1
release    : 2
source     :
    - https://github.com/ROCmSoftwarePlatform/rocSOLVER/archive/refs/tags/rocm-5.5.1.tar.gz : 8bf843e42d2e89203ea5fdb6e6082cea90da8d02920ab4c09bcc2b6f69909760
license    : MIT
component  : programming.library
summary    : Next generation LAPACK implementation for ROCm platform
description: |
    rocSOLVER is a work-in-progress implementation of a subset of LAPACK functionality on the ROCm platform.
clang      : yes
cache      : no
builddeps  :
    - pkgconfig(fmt)
    - rocblas-devel
    - rocminfo
    - rocm-cmake
    - rocm-compilersupport-devel
    - rocm-device-libs-devel
    - rocm-hip-devel
    - rocm-opencl-devel
    - rocm-runtime-devel
    - rocm-smi-devel
environment: |
    declare -A rocm_vars
    rocm_vars=(
        ["HIP_DEVICE_LIB_PATH"]="/usr/share/amdgcn/bitcode"
        ["DEVICE_LIB_PATH"]="/usr/share/amdgcn/bitcode"
        ["HIP_CLANG_PATH"]="/usr/bin"
        ["HIP_COMPILER"]="clang"
        ["HIP_LIB_PATH"]="/usr/lib64"
        ["HIP_PATH"]="/usr"
        ["HIP_PLATFORM"]="amd"
        ["HIP_ROCCLR_HOME"]="/usr"
        ["ROCM_PATH"]="/usr"
        ["AMDGPU_TARGETS"]="gfx1030"
        ["HCC_AMDGPU_TARGETS"]="gfx1030"
        ["BUILD_FILE_REORG_BACKWARD_COMPATIBILITY"]="OFF"
        ["HIPCC_VERBOSE"]="0"
    )

    for name in "${!rocm_vars[@]}"; do
        echo "Setting $name to ${rocm_vars[$name]}";
        export "$name"="${rocm_vars[$name]}";
        export ROCM_CMAKE_FLAGS="$ROCM_CMAKE_FLAGS -D$name=${rocm_vars[$name]}";
    done

    unset CFLAGS
    unset CXXFLAGS
    unset LDFLAGS
    export CXXFLAGS="-fcf-protection=none -mllvm -amdgpu-opt-vgpr-liverange=0"
setup      : |
    %cmake_ninja $ROCM_CMAKE_FLAGS \
                 -DROCSOLVER_EMBED_FMT=ON \
build      : |
    %ninja_build
install    : |
    %ninja_install
