name       : hsa-amd-aqlprofile
version    : 5.5.1
release    : 1
source     :
    - https://repo.radeon.com/rocm/apt/5.5.1/pool/main/h/hsa-amd-aqlprofile5.5.1/hsa-amd-aqlprofile5.5.1_1.0.0.50501-74~22.04_amd64.deb : 45af0acb1e39571cc4a115b58660507133134e171eacf9bbb28c4210a332cf10
license    : EULA
component  : programming.library
summary    : Some proprietary library needed for roctracer that I don't even know what it does
description: |
    Some proprietary library needed for roctracer that I don't even know what it does
extract    : no
builddeps  :
    - pkgconfig(numa)
    - pkgconfig(libdrm_amdgpu)
    - rocm-runtime-devel
    - tree
setup      : |
    ar x $sources/hsa-amd-aqlprofile5.5.1_1.0.0.50501-74~22.04_amd64.deb
    tar xf data.tar.xz
install    : |
    mkdir -p $installdir/usr
    cp -r opt/rocm-%version%/{lib,share} $installdir/usr/
