name       : rocm-core
version    : 5.5.1
release    : 1
source     :
    - https://github.com/RadeonOpenCompute/rocm-core/archive/refs/tags/rocm-5.5.1.tar.gz : bc73060432ffdc2e210394835d383890b9652476074ef4708d447473f273ce76
license    : MIT
component  : programming.library
summary    : A utility which can be used to get ROCm release version.
description: |
    rocm-core is a utility which can be used to get ROCm release version. It also provides the Lmod modules files for the ROCm release. The getROCmVersion function provides the ROCm version. 
clang      : yes
environment: |
    # They fricked up when appending linker flags
    unset LDFLAGS
setup      : |
    %cmake_ninja -DROCM_VERSION=%version%
build      : |
    %ninja_build
install    : |
    %ninja_install
