name       : hsakmt
version    : 5.2.3
release    : 2
source     :
    - https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface/archive/rocm-5.2.3.tar.gz : 8d313b8fd945a8d7248c00a2de9a2ee896fe77e464430a91b63400a986ec0bf0
license    : NCSA
component  : xorg.driver
clang      : yes
summary    : libhsakmt (HSA thunk) libraries for AMD KFD
description: |
    libhsakmt (HSA thunk) libraries for AMD KFD
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(libpci)
    - pkgconfig(numa)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
