name       : rocrand
version    : 5.2.3
release    : 1
source     :
    - git|https://github.com/ROCmSoftwarePlatform/rocRAND : 83617dcee431cb72d1e22c04320f79819b7c7ff4
license    : MIT
component  : programming.library
summary    : RAND library for HIP programming language 
description: |
    rocRAND provides functions that generate pseudo-random and quasi-random numbers. It is implemented in the HIP programming language and optimised for AMD's latest discrete GPUs. It is designed to run on top of AMD's Radeon Open Compute ROCm runtime, but it also works on CUDA enabled GPUs.
clang      : yes
builddeps  :
    - rocminfo
    - rocm-cmake
    - rocm-compilersupport-devel
    - rocm-device-libs-devel
    - rocm-hip-devel
    - rocm-opencl-devel
    - rocm-runtime-devel
    - rocm-smi-devel
    - git
environment: |
    export CCACHE_MAXSIZE=100G

    export ROCM_PATH=%PREFIX%
    export ROCM_DIR=%PREFIX%

    export HIP_PLATFORM=amd
    export HIP_RUNTIME=rocclr
    export DEVICE_LIB_PATH=/usr/lib64/amdgcn/bitcode
    export HIP_DEVICE_LIB_PATH=/usr/lib64/amdgcn/bitcode
    export HSA_PATH=/usr/hsa
    export LLVM_PATH=/usr
setup      : |
    %cmake_ninja -DCMAKE_CXX_COMPILER=/usr/bin/hipcc \
                 -DBUILD_HIPRAND=ON \
                 -DAMDGPU_TARGETS='gfx1030' #limiting compilation to just one GPU speeds up build time massively
build      : |
    %ninja_build
install    : |
    %ninja_install
