name       : rocprofiler
version    : 5.5.1
release    : 1
source     :
    - https://github.com/ROCm-Developer-Tools/rocprofiler/archive/refs/tags/rocm-5.5.1.tar.gz : f5dbece5c205e37383fed4a2bd6042ff1c11f11f64dfbf65d7e23c0af6889a5a
    - https://github.com/ROCm-Developer-Tools/roctracer/archive/refs/tags/rocm-5.5.1.tar.gz#roctracer-5.5.1.tar.gz : 3afc31ebfdb14b0365185ca6b9326a83b1503a94a51d910f5ce7ced192d8c133
# version    : 5.2.1
# release    : 1
# source     :
#     - https://github.com/ROCm-Developer-Tools/rocprofiler/archive/refs/tags/rocm-5.2.1.tar.gz : c6768ec428590aadfb0e7ef6e22b8dc5ac8ed97babeb56db07f2d5d41cd122e2
#     - https://github.com/ROCm-Developer-Tools/roctracer/archive/refs/tags/rocm-5.2.1.tar.gz#roctracer-5.2.1.tar.gz : e200b5342bdf840960ced6919d4bf42c8f30f8013513f25a2190ee8767667e59
license    : MIT
component  : programming.library
summary    : ROCm profiler library with perf-counters and derived metrics. 
description: |
    Profiling with metrics and traces based on perfcounters (PMC) and traces (SPM). Implementation is based on AqlProfile HSA extension.
patterns   : /*
clang      : yes
builddeps  :
    - pkgconfig(libhsakmt)
    - pkgconfig(numa) # Can't disable tests...
    - pkgconfig(libdrm_amdgpu)
    - pkgconfig(libelf)
    - pkgconfig(libdw)
    - rocminfo
    - rocm-cmake
    - rocm-compilersupport-devel
    - rocm-device-libs-devel
    - rocm-hip-devel
    - rocm-opencl-devel
    - rocm-runtime-devel
    - rocm-smi-devel
    - rocprim-devel
    - hsa-amd-aqlprofile-devel
    - git
    - python-lxml # why???
    - python-cppheaderparser
    - python-ply
    - gtest-devel
environment: |
    declare -A rocm_vars
    rocm_vars=(
        ["HIP_DEVICE_LIB_PATH"]="/usr/share/amdgcn/bitcode"
        ["DEVICE_LIB_PATH"]="/usr/share/amdgcn/bitcode"
        ["HIP_CLANG_PATH"]="/usr/bin"
        ["HIP_COMPILER"]="clang"
        ["HIP_LIB_PATH"]="/usr/lib64"
        ["HIP_PATH"]="/usr"
        ["HIP_PLATFORM"]="amd"
        ["HIP_ROCCLR_HOME"]="/usr"
        ["ROCM_PATH"]="/usr"
        ["AMDGPU_TARGETS"]="gfx1030"
        ["GPU_TARGETS"]="gfx1030"
        ["HCC_AMDGPU_TARGETS"]="gfx1030"
        ["BUILD_FILE_REORG_BACKWARD_COMPATIBILITY"]="OFF"
        ["HIPCC_VERBOSE"]="0"
    )

    for name in "${!rocm_vars[@]}"; do
        echo "Setting $name to ${rocm_vars[$name]}";
        export "$name"="${rocm_vars[$name]}";
        export ROCM_CMAKE_FLAGS="$ROCM_CMAKE_FLAGS -D$name=${rocm_vars[$name]}";
    done

    unset CFLAGS
    unset CXXFLAGS
    unset LDFLAGS
    export CXXFLAGS="-fcf-protection=none -mllvm -amdgpu-opt-vgpr-liverange=0"

    export ROCM_ROOT_DIR=%PREFIX%
    export ROCTRACER_DIR=$sources/roctracer-rocm-%version%
setup      : |
    tar xf $sources/roctracer-%version%.tar.gz -C $sources

    %patch -p1 < $pkgfiles/set_gputargets_correctly.diff
    # %patch -p1 < $pkgfiles/disable_tests.diff
    sed -i "s/add_subdirectory(plugin)//" CMakeLists.txt
    sed -i "s/add_subdirectory(samples)//" CMakeLists.txt
    %cmake_ninja $ROCM_CMAKE_FLAGS \
                 -DCMAKE_CXX_COMPILER=/usr/bin/hipcc \
                 -DPROF_API_HEADER_PATH="$ROCTRACER_DIR/inc/ext" \
                 -L \
build      : |
    %ninja_build
install    : |
    %ninja_install

    rm -rf $installdir/usr/rocprofiler
    rm -rf $installdir/usr/share/rocprofiler
