name       : rocprim
version    : 2.13.0
release    : 2
source     :
    - https://github.com/ROCmSoftwarePlatform/rocPRIM/archive/refs/tags/rocm-5.5.1.tar.gz : 63cdc682afb39efd18f097faf695ce64c851c4a550a8ad96fa89d694451b6a42
license    : MIT
component  : programming.library
summary    : ROCm Parallel Primitives
description: |
    rocPRIM is a header-only library providing HIP parallel primitives for developing performant GPU-accelerated code on AMD ROCm platform.
clang      : yes
builddeps  :
    - rocminfo
    - rocm-cmake
    - rocm-compilersupport-devel
    - rocm-device-libs-devel
    - rocm-hip-devel
    - rocm-opencl-devel
    - rocm-runtime-devel
    - rocm-smi-devel
    # - git
environment: |
    declare -A rocm_vars
    rocm_vars=(
        ["HIP_DEVICE_LIB_PATH"]="/usr/share/amdgcn/bitcode"
        ["HIP_CLANG_PATH"]="/usr/bin"
        ["HIP_COMPILER"]="clang"
        ["HIP_LIB_PATH"]="/usr/lib64"
        ["HIP_PATH"]="/usr"
        ["HIP_PLATFORM"]="amd"
        ["HIP_ROCCLR_HOME"]="/usr"
        ["ROCM_PATH"]="/usr"
        ["AMDGPU_TARGETS"]="gfx1030;gfx1032"
        ["BUILD_FILE_REORG_BACKWARD_COMPATIBILITY"]="OFF"
    )

    for name in "${!rocm_vars[@]}"; do
        echo "Setting $name to ${rocm_vars[$name]}";
        export "$name"="${rocm_vars[$name]}";
        export ROCM_CMAKE_FLAGS="$ROCM_CMAKE_FLAGS -D$name=${rocm_vars[$name]}";
    done
setup      : |
    # Oops, this patch is for rocSPARSE
    # %patch -p1 < $pkgfiles/dpp_fixes.patch
    %cmake_ninja $ROCM_CMAKE_FLAGS
build      : |
    %ninja_build
install    : |
    %ninja_install
