name       : hipsparse
version    : 5.2.3
release    : 1
source     :
    - https://github.com/ROCmSoftwarePlatform/hipSPARSE/archive/refs/tags/rocm-5.2.3.tar.gz : f70d3deff13188adc4105ef3ead53510e4b54075b9ffcfe3d3355d90d4b6eadd
license    : MIT
component  : programming.library
summary    : ROCm SPARSE marshalling library 
description: |
    hipSPARSE is a SPARSE marshalling library, with multiple supported backends. It sits between the application and a 'worker' SPARSE library, marshalling inputs into the backend library and marshalling results back to the application. hipSPARSE exports an interface that does not require the client to change, regardless of the chosen backend. Currently, hipSPARSE supports rocSPARSE and cuSPARSE as backends.
clang      : yes
builddeps  :
    - rocsparse-devel
    - rocminfo
    - rocm-cmake
    - rocm-compilersupport-devel
    - rocm-device-libs-devel
    - rocm-hip-devel
    - rocm-opencl-devel
    - rocm-runtime-devel
    - rocm-smi-devel
    - git
environment: |
    export CCACHE_MAXSIZE=100G

    export ROCM_PATH=%PREFIX%
    export ROCM_DIR=%PREFIX%

    export HIP_PLATFORM=amd
    export HIP_RUNTIME=rocclr
    export DEVICE_LIB_PATH=/usr/lib64/amdgcn/bitcode
    export HIP_DEVICE_LIB_PATH=/usr/lib64/amdgcn/bitcode
    export HIP_COMPILER=clang
    export HIP_CLANG_PATH=/usr/bin
    export HSA_PATH=/usr/hsa
    export LLVM_PATH=/usr

    # https://github.com/ROCm-Developer-Tools/HIP/blob/rocm-5.1.x/docs/markdown/clang_options.md
    # export CFLAGS="-fcf-protection=none"
    # export CXXFLAGS="-fcf-protection=none"
setup      : |
    %cmake_ninja -DAMDGPU_TARGETS='gfx1030' #limiting compilation to just one GPU speeds up build time massively
build      : |
    %ninja_build
install    : |
    %ninja_install
