name       : rocm-compilersupport
version    : 5.2.3
release    : 2
source     :
    - https://github.com/RadeonOpenCompute/ROCm-CompilerSupport/archive/refs/tags/rocm-5.2.3.tar.gz : 36d67dbe791d08ad0a02f0f3aedd46059848a0a232c5f999670103b0410c89dc
license    : NCSA
component  : programming.devel
homepage   : https://github.com/RadeonOpenCompute
summary    : The AMD Code Object Manager (Comgr)
description: |
    The AMD Code Object Manager (Comgr) is a shared library which provides operations for creating and inspecting code objects.
# avx2       : yes
# optimize   :
#     - speed
#     - lto
clang      : yes
builddeps  :
    - rocm-cmake
    - rocm-device-libs-devel
setup      : |
    %apply_patches

    sed -i -e "/compile_test/d" \
           -e "/compile_minimal_test/d" \
           -e "/compile_device_libs_test/d" \
           -e "/compile_source_with_device_libs_to_bc_test/d" \
           lib/comgr/test/CMakeLists.txt
    sed -i '/Args.push_back(HIPIncludePath/,+1d' lib/comgr/src/comgr-compiler.cpp
    sed -i '/Args.push_back(ROCMIncludePath/,+1d' lib/comgr/src/comgr-compiler.cpp
    sed -i 's/lib\(\/clang\)/%{_lib}\1/' lib/comgr/src/comgr-compiler.cpp

    %cmake -S lib/comgr -DBUILD_TESTING=ON
build      : |
    %make
install    : |
    %make_install

    #remove textfiles that are not useful for the users
    rm -r %installroot%/usr/share
# If you have an AMD GPU:
# check      : |
#     make test
